package com.example.composecatalog.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val qvc_light_primary = Color(0xFFAD3035)
val qvc_light_onPrimary = Color(0xFFFFFFFF)
val qvc_light_primaryContainer = Color(0xFFFFDAD8)
val qvc_light_onPrimaryContainer = Color(0xFF410006)
val qvc_light_secondary = Color(0xFF9C4238)
val qvc_light_onSecondary = Color(0xFFFFFFFF)
val qvc_light_secondaryContainer = Color(0xFFFFDAD5)
val qvc_light_onSecondaryContainer = Color(0xFF410001)
val qvc_light_tertiary = Color(0xFF006874)
val qvc_light_onTertiary = Color(0xFFFFFFFF)
val qvc_light_tertiaryContainer = Color(0xFF96F0FF)
val qvc_light_onTertiaryContainer = Color(0xFF001F24)
val qvc_light_error = Color(0xFFBA1A1A)
val qvc_light_errorContainer = Color(0xFFFFDAD6)
val qvc_light_onError = Color(0xFFFFFFFF)
val qvc_light_onErrorContainer = Color(0xFF410002)
val qvc_light_background = Color(0xFFFFFBFF)
val qvc_light_onBackground = Color(0xFF201A1A)
val qvc_light_surface = Color(0xFFFFFBFF)
val qvc_light_onSurface = Color(0xFF201A1A)
val qvc_light_surfaceVariant = Color(0xFFF4DDDC)
val qvc_light_onSurfaceVariant = Color(0xFF534342)
val qvc_light_outline = Color(0xFF857372)
val qvc_light_inverseOnSurface = Color(0xFFFBEEED)
val qvc_light_inverseSurface = Color(0xFF362F2E)
val qvc_light_inversePrimary = Color(0xFFFFB3B0)
val qvc_light_shadow = Color(0xFF000000)
val qvc_light_surfaceTint = Color(0xFFAD3035)
val qvc_light_outlineVariant = Color(0xFFD7C1C0)
val qvc_light_scrim = Color(0xFF000000)

val qvc_dark_primary = Color(0xFFFFB3B0)
val qvc_dark_onPrimary = Color(0xFF68000F)
val qvc_dark_primaryContainer = Color(0xFF8C1620)
val qvc_dark_onPrimaryContainer = Color(0xFFFFDAD8)
val qvc_dark_secondary = Color(0xFFFFB4AA)
val qvc_dark_onSecondary = Color(0xFF5F1510)
val qvc_dark_secondaryContainer = Color(0xFF7D2B23)
val qvc_dark_onSecondaryContainer = Color(0xFFFFDAD5)
val qvc_dark_tertiary = Color(0xFF4FD8EB)
val qvc_dark_onTertiary = Color(0xFF00363D)
val qvc_dark_tertiaryContainer = Color(0xFF004F57)
val qvc_dark_onTertiaryContainer = Color(0xFF96F0FF)
val qvc_dark_error = Color(0xFFFFB4AB)
val qvc_dark_errorContainer = Color(0xFF93000A)
val qvc_dark_onError = Color(0xFF690005)
val qvc_dark_onErrorContainer = Color(0xFFFFDAD6)
val qvc_dark_background = Color(0xFF201A1A)
val qvc_dark_onBackground = Color(0xFFEDE0DE)
val qvc_dark_surface = Color(0xFF201A1A)
val qvc_dark_onSurface = Color(0xFFEDE0DE)
val qvc_dark_surfaceVariant = Color(0xFF534342)
val qvc_dark_onSurfaceVariant = Color(0xFFD7C1C0)
val qvc_dark_outline = Color(0xFFA08C8B)
val qvc_dark_inverseOnSurface = Color(0xFF201A1A)
val qvc_dark_inverseSurface = Color(0xFFEDE0DE)
val qvc_dark_inversePrimary = Color(0xFFAD3035)
val qvc_dark_shadow = Color(0xFF000000)
val qvc_dark_surfaceTint = Color(0xFFFFB3B0)
val qvc_dark_outlineVariant = Color(0xFF534342)
val qvc_dark_scrim = Color(0xFF000000)